FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# Foodma

API for foodma App. Base URL : https://private-4b16e-foodma.apiary-mock.com/

## Token Refresh [/token_refresh]

### Token Refresh [POST]

+ Request (application/json)

        {
            "token": "elxkjkjskjzvkjhkjkjjhckjhkjkzjhkjbkjbkjszcv"
        }
        
+ Response 200 (application/json)

        {
            "status": "success",
            "message": "token successfully refreshed",
            "data": {
                        "token": "fbdbedzsdzdgnsdgnsdfgsrtjn"
            }
        
        }
        
## Login [/login]

### Login [POST]

+ Request (application/json)

        {
            "email": "xxx@yyy.com",
            "password": "password"
        }
        
+ Response 200 (application/json)

        {
            "status": "success",
            "message": "user successfully logged in",
            "data": {
                        "token": "elxkjkjskjzvkjhkjkjjhckjhkjkzjhkjbkjbkjszcv"
            }
        
        }
        
        
## Register [/register]

### Register [POST]

+ Request (application/json)

        {
            "name": "abcd",
            "email": "abcd@efg.com",
            "password": "password",
            "phone": "9037324059",
            "gender": "Male"
        }
        
+ Response 200 (application/json)

        {
            "status": "success",
            "message": "account successfully created",
        
        }
        
        
## Forgot Password [/reset_password]

### Register [POST]

+ Request (application/json)

        {
            "phone": "9037324058",
        }
        
+ Response 200 (application/json)

        {
            "status": "success",
            "message": "OTP sent to phone",
            "data":"1234"
        
        }