FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# Foodma

API for foodma App. Base URL : https://private-4b16e-foodma.apiary-mock.com/

## Token Refresh [/token_refresh]

### Token Refresh [POST]

+ Request (application/json)

        {
            "token": "elxkjkjskjzvkjhkjkjjhckjhkjkzjhkjbkjbkjszcv"
        }
        
+ Response 200 (application/json)

        {
            "status": "success",
            "message": "token successfully refreshed",
            "data": {
                        "token": "fbdbedzsdzdgnsdgnsdfgsrtjn"
            }
        
        }
        
## Login [/login]

### Login [POST]

+ Request (application/json)

        {
            "email": "xxx@yyy.com",
            "password": "password"
        }
        
+ Response 200 (application/json)

        {
            "status": "success",
            "message": "user successfully logged in",
            "data": {
                        "token": "elxkjkjskjzvkjhkjkjjhckjhkjkzjhkjbkjbkjszcv"
            }
        
        }
        
        
## Register [/register]

### Register [POST]

+ Request (application/json)

        {
            "name": "abcd",
            "email": "abcd@efg.com",
            "password": "password",
            "phone": "9037324059",
            "gender": "Male"
        }
        
+ Response 200 (application/json)

        {
            "status": "success",
            "message": "account successfully created"
        
        }
        
        
## Forgot Password [/reset_password]

### Forgot Password [POST]

+ Request (application/json)

        {
            "phone": "9037324058"
        }
        
+ Response 200 (application/json)

        {
            "status": "success",
            "message": "OTP sent to phone",
            "data":"1234"
        
        }
        
## Edit Password [/change_password]

### Create Password and Change Password [POST]

+ Request (application/json)

        {
            "current_password": "password",
            "new_password": "password"
        }
        
+ Response 200 (application/json)

        {
            "status": "success",
            "message": "Password changed successfully"
        }
        
## Configuration [/configuration]

### Configuration [GET]

+ Request (application/json)

        {
            "platform": "Android"
        }
        
+ Response 200 (application/json)

        {
            "status": "success",
            "message": "Password changed successfully"
            "data":{
                        "update_version":"1.0.1",
                        "force_update": true
                    }
        }
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
## Home Page [/home_page]

### Home Page [GET]

+ Header (application/json)

        {
            "Authorization":"Bearer dasljhvlaskvaf"
        }
        
+ Response 200 (application/json)

        {
            "status": "success",
            "message": "Successfully listed",
            "data":{
            
                       "notification_count":5,
                       "banner":[{"category_id":1,"category_name":"Category 1","image":"https://i.ibb.co/7kTRJY7/banner-1.png"},
                                {"category_id":2,"category_name":"Category 2","image":"https://i.ibb.co/87v1gLc/banner-2.png"},
                                {"category_id":3,"category_name":"Category 3","image":"https://i.ibb.co/7kTRJY7/banner-1.png"},
                                {"category_id":4,"category_name":"Category 4","image":"https://i.ibb.co/87v1gLc/banner-2.png"}],
                       "categories":[{"id":1,"image":"https://i.ibb.co/zNKPx5B/food-item-thumb.jpg","title":"Category 1"},
                                    {"id":2,"image":"https://i.ibb.co/zNKPx5B/food-item-thumb.jpg","title":"Category 2"},
                                    {"id":3,"image":"https://i.ibb.co/zNKPx5B/food-item-thumb.jpg","title":"Category 3"},
                                    {"id":4,"image":"https://i.ibb.co/zNKPx5B/food-item-thumb.jpg","title":"Category 4"},
                                    {"id":5,"image":"https://i.ibb.co/zNKPx5B/food-item-thumb.jpg","title":"Category 5"},
                                    {"id":6,"image":"https://i.ibb.co/zNKPx5B/food-item-thumb.jpg","title":"Category 6"}],
                       "super_sale": [{
                                            "id":1,
                                            "category_id":1,
                                            "image":"https://i.ibb.co/GtymPQB/product-3.png",
                                            "product_title":"Similar product 1",
                                            "short_description":"Continental, Pan - Asian",
                                            "discount":"35% Off | Coupon Foodma50",
                                            "price":"100"
                                        },
                                        {
                                            "id":2,
                                            "category_id":1,
                                            "image":"https://i.ibb.co/RT4PGPp/product-4.png",
                                            "product_title":"Similar product 2",
                                            "short_description":"Continental, Pan - Asian",
                                            "discount":"35% Off | Coupon Foodma50",
                                            "price":"100"
                                        }],
                        "first_ad":[{"id":1,"category_id":1,"image":"https://i.ibb.co/zHJ9Pwg/first-ad-1.png"},
                                    {"id":2,"category_id":1,"image":"https://i.ibb.co/37z8VLW/first-ad-2.png"},
                                    {"id":3,"category_id":1,"image":"https://i.ibb.co/zHJ9Pwg/first-ad-1.png"},
                                    {"id":4,"category_id":1,"image":"https://i.ibb.co/37z8VLW/first-ad-2.png"}],
                        "frequently_bought":{
                                                "product_one":{"id":1,"category_id":1,"image":"https://i.ibb.co/vh6QKh0/raisin-1.png","title":"Raisin 100ml","price":"100"},
                                                "product_two":{"id":2,"category_id":1,"image":"https://i.ibb.co/JkvVSj3/raisin-2.png","title":"Raisin 100ml","price":"100"},
                                                "product_three":{"id":3,"category_id":1,"image":"https://i.ibb.co/71Xqmj6/raisin-3.png","title":"Raisin 100ml","price":"100"}
                                            },
                        "second_ad":[{"id":1,"category_id":1,"image":"https://i.ibb.co/hZn71tZ/third-ad-3.png"},
                                    {"id":2,"category_id":1,"image":"https://i.ibb.co/gFrL83w/third-ad-2.png"}],
                        "deals_of_day":{
                                                "product_one":{"id":1,"category_id":1,"image":"https://i.ibb.co/vh6QKh0/raisin-1.png","title":"Raisin 100ml","price":"100"},
                                                "product_two":{"id":2,"category_id":1,"image":"https://i.ibb.co/JkvVSj3/raisin-2.png","title":"Raisin 100ml","price":"100"},
                                                "product_three":{"id":3,"category_id":1,"image":"https://i.ibb.co/71Xqmj6/raisin-3.png","title":"Raisin 100ml","price":"100"}
                                            },
                        "third_ad":[{"id":1,"category_id":1,"image":"https://i.ibb.co/ByDt5gn/third-ad-1.png"},
                                    {"id":2,"category_id":1,"image":"https://i.ibb.co/gFrL83w/third-ad-2.png"},
                                    {"id":3,"category_id":1,"image":"https://i.ibb.co/hZn71tZ/third-ad-3.png"}]
                    }
        }
        
        
        
## Category Listing [/categories]

### Category Listing [GET]

+ Header (application/json)

        {
            "Authorization":"Bearer dasljhvlaskvaf"
        }
       
+ Response 200 (application/json)

        {
            "status": "success",
            "message": "Listed successfully",
            "data":[
                     {"id":1,"name":"Category 1","sub_categories":[{"id":1,"name":"Sub Category 1","category_items":[{"id":1,"name":"Category Item 1"},
                                                                                                                    {"id":2,"name":"Category Item 2"},
                                                                                                                    {"id":3,"name":"Category Item 3"},
                                                                                                                    {"id":4,"name":"Category Item 4"},
                                                                                                                    {"id":5,"name":"Category Item 5"}]},
                                                {"id":2,"name":"Sub Category 2","category_items":[{"id":6,"name":"Category Item 1"},
                                                                                                                    {"id":7,"name":"Category Item 2"},
                                                                                                                    {"id":8,"name":"Category Item 3"},
                                                                                                                    {"id":9,"name":"Category Item 4"},
                                                                                                                    {"id":10,"name":"Category Item 5"}]},
                                                {"id":3,"name":"Sub Category 3","category_items":[{"id":11,"name":"Category Item 1"},
                                                                                                                    {"id":12,"name":"Category Item 2"},
                                                                                                                    {"id":13,"name":"Category Item 3"},
                                                                                                                    {"id":14,"name":"Category Item 4"},
                                                                                                                    {"id":15,"name":"Category Item 5"}]},
                                                {"id":4,"name":"Sub Category 4","category_items":[{"id":16,"name":"Category Item 1"},
                                                                                                                    {"id":17,"name":"Category Item 2"},
                                                                                                                    {"id":18,"name":"Category Item 3"},
                                                                                                                    {"id":19,"name":"Category Item 4"},
                                                                                                                    {"id":20,"name":"Category Item 5"}]},
                                                {"id":5,"name":"Sub Category 5","category_items":[{"id":21,"name":"Category Item 1"},
                                                                                                                    {"id":22,"name":"Category Item 2"},
                                                                                                                    {"id":23,"name":"Category Item 3"},
                                                                                                                    {"id":24,"name":"Category Item 4"},
                                                                                                                    {"id":25,"name":"Category Item 5"}]},
                                                {"id":6,"name":"Sub Category 6","category_items":[{"id":26,"name":"Category Item 1"},
                                                                                                                    {"id":27,"name":"Category Item 2"},
                                                                                                                    {"id":28,"name":"Category Item 3"},
                                                                                                                    {"id":29,"name":"Category Item 4"},
                                                                                                                    {"id":30,"name":"Category Item 5"}]},
                                                {"id":7,"name":"Sub Category 7","category_items":[{"id":31,"name":"Category Item 1"},
                                                                                                                    {"id":32,"name":"Category Item 2"},
                                                                                                                    {"id":33,"name":"Category Item 3"},
                                                                                                                    {"id":34,"name":"Category Item 4"},
                                                                                                                    {"id":35,"name":"Category Item 5"}]},
                                                {"id":8,"name":"Sub Category 8","category_items":[{"id":36,"name":"Category Item 1"},
                                                                                                                    {"id":37,"name":"Category Item 2"},
                                                                                                                    {"id":38,"name":"Category Item 3"},
                                                                                                                    {"id":39,"name":"Category Item 4"},
                                                                                                                    {"id":40,"name":"Category Item 5"}]}]},
                     {"id":2,"name":"Category 2","sub_categories":[{"id":9,"name":"Sub Category 1","category_items":[{"id":41,"name":"Category Item 1"}]},
                                                {"id":10,"name":"Sub Category 2","category_items":[{"id":10,"name":"Category Item 1"}]},
                                                {"id":11,"name":"Sub Category 3","category_items":[{"id":11,"name":"Category Item 1"}]},
                                                {"id":12,"name":"Sub Category 4","category_items":[{"id":12,"name":"Category Item 1"}]},
                                                {"id":13,"name":"Sub Category 5","category_items":[{"id":13,"name":"Category Item 1"}]},
                                                {"id":14,"name":"Sub Category 6","category_items":[{"id":14,"name":"Category Item 1"}]},
                                                {"id":15,"name":"Sub Category 7","category_items":[{"id":15,"name":"Category Item 1"}]},
                                                {"id":16,"name":"Sub Category 8","category_items":[{"id":16,"name":"Category Item 1"}]}]},
                     {"id":3,"name":"Category 3","sub_categories":[{"id":17,"name":"Sub Category 1","category_items":[{"id":17,"name":"Category Item 1"}]},
                                                {"id":18,"name":"Sub Category 2","category_items":[{"id":18,"name":"Category Item 1"}]},
                                                {"id":19,"name":"Sub Category 3","category_items":[{"id":19,"name":"Category Item 1"}]},
                                                {"id":20,"name":"Sub Category 4","category_items":[{"id":20,"name":"Category Item 1"}]},
                                                {"id":21,"name":"Sub Category 5","category_items":[{"id":21,"name":"Category Item 1"}]},
                                                {"id":22,"name":"Sub Category 6","category_items":[{"id":22,"name":"Category Item 1"}]},
                                                {"id":23,"name":"Sub Category 7","category_items":[{"id":23,"name":"Category Item 1"}]},
                                                {"id":24,"name":"Sub Category 8","category_items":[{"id":24,"name":"Category Item 1"}]}]},
                     {"id":4,"name":"Category 4","sub_categories":[{"id":25,"name":"Sub Category 1","category_items":[{"id":25,"name":"Category Item 1"}]},
                                                {"id":26,"name":"Sub Category 2","category_items":[{"id":26,"name":"Category Item 1"}]},
                                                {"id":27,"name":"Sub Category 3","category_items":[{"id":27,"name":"Category Item 1"}]},
                                                {"id":28,"name":"Sub Category 4","category_items":[{"id":28,"name":"Category Item 1"}]},
                                                {"id":29,"name":"Sub Category 5","category_items":[{"id":29,"name":"Category Item 1"}]},
                                                {"id":30,"name":"Sub Category 6","category_items":[{"id":30,"name":"Category Item 1"}]},
                                                {"id":31,"name":"Sub Category 7","category_items":[{"id":31,"name":"Category Item 1"}]},
                                                {"id":32,"name":"Sub Category 8","category_items":[{"id":32,"name":"Category Item 1"}]}]},
                     {"id":5,"name":"Category 5","sub_categories":[{"id":33,"name":"Sub Category 1","category_items":[{"id":33,"name":"Category Item 1"}]},
                                                {"id":34,"name":"Sub Category 2","category_items":[{"id":34,"name":"Category Item 1"}]},
                                                {"id":35,"name":"Sub Category 3","category_items":[{"id":35,"name":"Category Item 1"}]},
                                                {"id":36,"name":"Sub Category 4","category_items":[{"id":36,"name":"Category Item 1"}]},
                                                {"id":37,"name":"Sub Category 5","category_items":[{"id":37,"name":"Category Item 1"}]},
                                                {"id":38,"name":"Sub Category 6","category_items":[{"id":38,"name":"Category Item 1"}]},
                                                {"id":39,"name":"Sub Category 7","category_items":[{"id":39,"name":"Category Item 1"}]},
                                                {"id":40,"name":"Sub Category 8","category_items":[{"id":40,"name":"Category Item 1"}]}]},
                     {"id":6,"name":"Category 6","sub_categories":[{"id":41,"name":"Sub Category 1","category_items":[{"id":41,"name":"Category Item 1"}]},
                                                {"id":42,"name":"Sub Category 2","category_items":[{"id":42,"name":"Category Item 1"}]},
                                                {"id":43,"name":"Sub Category 3","category_items":[{"id":43,"name":"Category Item 1"}]},
                                                {"id":44,"name":"Sub Category 4","category_items":[{"id":44,"name":"Category Item 1"}]},
                                                {"id":45,"name":"Sub Category 5","category_items":[{"id":45,"name":"Category Item 1"}]},
                                                {"id":46,"name":"Sub Category 6","category_items":[{"id":46,"name":"Category Item 1"}]},
                                                {"id":47,"name":"Sub Category 7","category_items":[{"id":47,"name":"Category Item 1"}]},
                                                {"id":48,"name":"Sub Category 8","category_items":[{"id":48,"name":"Category Item 1"}]}]}
                    ]
        }
        
        
## Filter [/filter/{category_id}]

### Filter [GET]

+ Header (application/json)

        {
            "Authorization":"Bearer dasljhvlaskvaf"
        }
        
+ Response 200 (application/json)

        {
            "status": "success",
            "message": "Listed successfully",
            "data": {
                        "min_price":1000,
                        "max_price":10000,
                        "interval":1000,
                        "categories":[{"id":1,"name":"Category","sub_categories":[{"id":1,"name":"Cashew bla vla"},
                                                                                {"id":2,"name":"Cashew Eleanore"},
                                                                                {"id":3,"name":"Cashew Victoria"},
                                                                                {"id":4,"name":"Cashew Eleanore"},
                                                                                {"id":5,"name":"Cashew nelicon"},
                                                                                {"id":6,"name":"Cashew Eleanore"},
                                                                                {"id":7,"name":"Cashew nelicon"}]},
                                    {"id":2,"name":"Brand","sub_categories":[{"id":8,"name":"Cashew nelicon"},
                                                                                {"id":9,"name":"Cashew Eleanore"},
                                                                                {"id":10,"name":"Cashew nelicon"},
                                                                                {"id":11,"name":"Cashew Eleanore"},
                                                                                {"id":12,"name":"Cashew Victoria"},
                                                                                {"id":13,"name":"Cashew Eleanore"},
                                                                                {"id":14,"name":"Cashew bla vla"}]},
                                    {"id":3,"name":"Type","sub_categories":[{"id":15,"name":"Cashew bla vla"},
                                                                                {"id":16,"name":"Cashew Eleanore"},
                                                                                {"id":17,"name":"Cashew nelicon"},
                                                                                {"id":18,"name":"Cashew Eleanore"},
                                                                                {"id":19,"name":"Cashew Victoria"},
                                                                                {"id":20,"name":"Cashew Eleanore"},
                                                                                {"id":21,"name":"Cashew bla vla"}]}
                                    ]}
            
            }
        
## Product Listing [/products]

### Product Listing [POST]

+ Header (application/json)

        {
            "Authorization":"Bearer dasljhvlaskvaf"
        }
        
+ Request (application/json)

        {
            "category_id":1, 
            "type_id":1, 
            "filter":"", 
            "sort":0, 
            "search":""
        }
        
+ Response 200 (application/json)

        {
            "status": "success",
            "message": "Listed successfully",
            "data":[                    {
                                            "id":1,
                                            "image":"https://i.ibb.co/GtymPQB/product-3.png",
                                            "product_title":"Product 1",
                                            "short_description":"Continental, Pan - Asian",
                                            "star_rating":"4.5",
                                            "actual_price":"200",
                                            "discounted_price":"100",
                                            "discount_percentage":"35"
                     
                                        },
                                        {
                                            "id":2,
                                            "image":"https://i.ibb.co/GtymPQB/product-3.png",
                                            "product_title":"Product 2",
                                            "short_description":"Continental, Pan - Asian",
                                            "star_rating":"4.5",
                                            "actual_price":"200",
                                            "discounted_price":"100",
                                            "discount_percentage":"35"
                                            
                                        },
                                        {   
                                            "id":3,
                                            "image":"https://i.ibb.co/GtymPQB/product-3.png",
                                            "product_title":"Product 3",
                                            "short_description":"Continental, Pan - Asian",
                                            "star_rating":"4.5",
                                            "actual_price":"200",
                                            "discounted_price":"100",
                                            "discount_percentage":"35"
                                        },
                                        {
                                            "id":4,
                                            "image":"https://i.ibb.co/GtymPQB/product-3.png",
                                            "product_title":"Product 4",
                                            "short_description":"Continental, Pan - Asian",
                                            "star_rating":"4.5",
                                            "actual_price":"200",
                                            "discounted_price":"100",
                                            "discount_percentage":"35"
                                        },
                                        {
                                            "id":5,
                                            "image":"https://i.ibb.co/GtymPQB/product-3.png",
                                            "product_title":"Product 5",
                                            "short_description":"Continental, Pan - Asian",
                                            "star_rating":"4.5",
                                            "actual_price":"200",
                                            "discounted_price":"100",
                                            "discount_percentage":"35"
                     
                                        },
                                        {
                                            "id":6,
                                            "image":"https://i.ibb.co/GtymPQB/product-3.png",
                                            "product_title":"Product 6",
                                            "short_description":"Continental, Pan - Asian",
                                            "star_rating":"4.5",
                                            "actual_price":"200",
                                            "discounted_price":"100",
                                            "discount_percentage":"35"
                                            
                                        },
                                        {   
                                            "id":7,
                                            "image":"https://i.ibb.co/GtymPQB/product-3.png",
                                            "product_title":"Product 7",
                                            "short_description":"Continental, Pan - Asian",
                                            "star_rating":"4.5",
                                            "actual_price":"200",
                                            "discounted_price":"100",
                                            "discount_percentage":"35"
                                        },
                                        {
                                            "id":8,
                                            "image":"https://i.ibb.co/GtymPQB/product-3.png",
                                            "product_title":"Product 8",
                                            "short_description":"Continental, Pan - Asian",
                                            "star_rating":"4.5",
                                            "actual_price":"200",
                                            "discounted_price":"100",
                                            "discount_percentage":"35"
                                        }
                    ]   
        }
        
        
## Search [/search/{key}]

### Search [GET]

+ Header (application/json)

        {
            "Authorization":"Bearer dasljhvlaskvaf"
        }
        
+ Response 200 (application/json)

        {
            "status": "success",
            "message": "Listed successfully",
            "data":[                    {
                                            "id":1,
                                            "category_id":1,
                                            "product_title":"Product 1"

                                        },
                                        {
                                            "id":2,
                                            "category_id":2,
                                            "product_title":"Product 2"
                                            
                                        },
                                        {   
                                            "id":3,
                                            "category_id":3,
                                            "product_title":"Product 3"
                                        },
                                        {
                                            "id":4,
                                            "category_id":4,
                                            "product_title":"Product 4"
                                        },
                                        {
                                            "id":5,
                                            "category_id":5,
                                            "product_title":"Product 5"
                     
                                        },
                                        {
                                            "id":6,
                                            "category_id":6,
                                            "product_title":"Product 6"
                                            
                                        },
                                        {   
                                            "id":7,
                                            "category_id":7,
                                            "product_title":"Product 7"
                                        },
                                        {
                                            "id":8,
                                            "category_id":8,
                                            "product_title":"Product 8"
                                        }
                    ]
        }
        
        
## Product Details [/product_details/{id}]

### Product Details [GET]

+ Header (application/json)

        {
            "Authorization":"Bearer dasljhvlaskvaf"
        }
        
+ Response 200 (application/json)

        {
            "status": "success",
            "message": "Listed successfully",
            "data":{
                     "product_images":["https://i.ibb.co/37z8VLW/first-ad-2.png",
                     "https://i.ibb.co/37z8VLW/first-ad-2.png",
                     "https://i.ibb.co/37z8VLW/first-ad-2.png",
                     "https://i.ibb.co/37z8VLW/first-ad-2.png"],
                     "short_description":"Continental, Pan Asian",
                     "product_title":"The bowl company Dal",
                     "price":"100",
                     "ratings_count": 2500,
                     "start_rating": 4.5,
                     "available_quantites": [{"id":1,"quantity":"100 gm"},{"id":2,"quantity":"200 gm"},{"id":3,"quantity":"300 gm"}],
                     "key_features":["Perfect blend of handpicked spices",
                     "Perfect blend of handpicked spices",
                     "Perfect blend of handpicked spices",
                     "Perfect blend of handpicked spices",
                     "Perfect blend of handpicked spices"],
                     "ingredients":"White salt,dry mango, etc",
                     "unit":"100g",
                     "shelf_life":"9 months",
                     "manufacturer_details":"Mahashian Di Hatti Pvt Ltd, DI 9/44 Kirti Nagar",
                     "similar_products":[{
                                            "id":1,
                                            "image":"https://i.ibb.co/GtymPQB/product-3.png",
                                            "product_title":"Similar product 1",
                                            "short_description":"Continental, Pan - Asian",
                                            "discount":"35% Off | Coupon Foodma50",
                                            "price":"100"
                     
                                        },
                                        {
                                            "id":2,
                                            "image":"https://i.ibb.co/GtymPQB/product-3.png",
                                            "product_title":"Similar product 2",
                                            "short_description":"Continental, Pan - Asian",
                                            "discount":"35% Off | Coupon Foodma50",
                                            "price":"100"
                                        },
                                        {   
                                            "id":3,
                                            "image":"https://i.ibb.co/GtymPQB/product-3.png",
                                            "product_title":"Similar product 3",
                                            "short_description":"Continental, Pan - Asian",
                                            "discount":"35% Off | Coupon Foodma50",
                                            "price":"100"
                                        },
                                        {
                                            "id":4,
                                            "image":"https://i.ibb.co/GtymPQB/product-3.png",
                                            "product_title":"Similar product 4",
                                            "short_description":"Continental, Pan - Asian",
                                            "discount":"35% Off | Coupon Foodma50",
                                            "price":"100"
                                        }],
                    "rating":{
                                "star_rating":"4.6",
                                "ratings_count":"2500",
                                "reviews":[
                                            {"id":1,"title":"Jacob Joseph","start_rating":"4","description":"Very good product. Nice quality"},
                                            {"id":2,"title":"Jacob Joseph","start_rating":"4","description":"Very good product. Nice quality"},
                                            {"id":3,"title":"Jacob Joseph","start_rating":"4","description":"Very good product. Nice quality"},
                                            {"id":4,"title":"Jacob Joseph","start_rating":"4","description":"Very good product. Nice quality"},
                                            {"id":5,"title":"Jacob Joseph","start_rating":"4","description":"Very good product. Nice quality"},
                                            {"id":6,"title":"Jacob Joseph","start_rating":"4","description":"Very good product. Nice quality"},
                                            {"id":7,"title":"Jacob Joseph","start_rating":"4","description":"Very good product. Nice quality"},
                                            {"id":8,"title":"Jacob Joseph","start_rating":"4","description":"Very good product. Nice quality"},
                                            {"id":9,"title":"Jacob Joseph","start_rating":"4","description":"Very good product. Nice quality"},
                                            {"id":10,"title":"Jacob Joseph","start_rating":"4","description":"Very good product. Nice quality"}
                                        ]
                                }
                            }       
        }
        
        
## Add to wishlist [/add_wishlist]

### Add to wishlist [POST]

+ Header (application/json)

        {
            "Authorization":"Bearer dasljhvlaskvaf"
        }
        
+ Request (application/json)

        {
            "product_id":1
        }
        
+ Response 200 (application/json)

        {
            "status": "success",
            "message": "Added successfully"
        }
        
        
## Add to cart [/add_cart]

### Add to cart [POST]

+ Header (application/json)

        {
            "Authorization":"Bearer dasljhvlaskvaf"
        }
        
+ Request (application/json)

        {
            "product_id":1,
            "quantity":20
        }
        
+ Response 200 (application/json)

        {
            "status": "success",
            "message": "Added successfully"
        }
        
        
## View cart [/cart]

### View cart [GET]

+ Header (application/json)

        {
            "Authorization":"Bearer dasljhvlaskvaf"
        }
        
+ Response 200 (application/json)

        {
            "status": "success",
            "message": "Listed successfully",
            "data":{
                    "total":"4500",
                    "products":[{"id":1,
                        "image":"https://i.ibb.co/GtymPQB/product-3.png",
                        "product_title":"Product 1",
                        "short_description":"Continental, Pan - Asian",
                        "actual_price":"200",
                        "quantity":"1",
                        "discounted_price":"100"
                        },
                        {"id":2,
                        "image":"https://i.ibb.co/GtymPQB/product-3.png",
                        "product_title":"Product 2",
                        "short_description":"Continental, Pan - Asian",
                        "actual_price":"200",
                        "quantity":"2",
                        "discounted_price":"100"
                        },
                        {"id":3,
                        "image":"https://i.ibb.co/GtymPQB/product-3.png",
                        "product_title":"Product 3",
                        "short_description":"Continental, Pan - Asian",
                        "actual_price":"200",
                        "quantity":"3",
                        "discounted_price":"100"
                        },
                        {"id":4,
                        "image":"https://i.ibb.co/GtymPQB/product-3.png",
                        "product_title":"Product 4",
                        "short_description":"Continental, Pan - Asian",
                        "actual_price":"200",
                        "quantity":"4",
                        "discounted_price":"100"
                        }]}
        }
        
        
## Change Quantity [/change_quantity]

### Change Quantity [POST]

+ Header (application/json)

        {
            "Authorization":"Bearer dasljhvlaskvaf"
        }
        
+ Request (application/json)

        {
            "product_id":1,
            "quantity":20
        }
        
+ Response 200 (application/json)

        {
            "status": "success",
            "message": "Quantity changed successfully"
        }
        
        
## Move to wishlist [/move_wishlist]

### Move to wishlist [POST]

+ Header (application/json)

        {
            "Authorization":"Bearer dasljhvlaskvaf"
        }
        
+ Request (application/json)

        {
            "product_id":1
        }
        
+ Response 200 (application/json)

        {
            "status": "success",
            "message": "Moved to wishlist successfully"
        }
        
## Remove from cart [/remove_cart/{product_id}]

### Remove from cart [POST]

+ Header (application/json)

        {
            "Authorization":"Bearer dasljhvlaskvaf"
        }
        
+ Response 200 (application/json)

        {
            "status": "success",
            "message": "Removed"
        }
        
        
## Checkout [/checkout]

### Checkout [POST]

+ Header (application/json)

        {
            "Authorization":"Bearer dasljhvlaskvaf"
        }
        
+ Response 200 (application/json)

        {
            "status": "success",
            "message": "checkout successfully"
        }
        
        
## Address Listing [/address_list]

### Address Listing [GET]

+ Header (application/json)

        {
            "Authorization":"Bearer dasljhvlaskvaf"
        }
        
+ Response 200 (application/json)

        {
            "status": "success",
            "message": "Listed successfully",
            "data":[]
        }
        
        
## Edit Address [/edit_address]

### Edit Address [POST]

+ Header (application/json)

        {
            "Authorization":"Bearer dasljhvlaskvaf"
        }
        
+ Request (application/json)

        {
            "address_id":1,
            "address":""
        }
        
+ Response 200 (application/json)

        {
            "status": "success",
            "message": "Address edited successfully"
        }
        
        
## Add New Address [/add_address]

### Add New Address [POST]

+ Header (application/json)

        {
            "Authorization":"Bearer dasljhvlaskvaf"
        }
        
+ Request (application/json)

        {
            "address":""
        }
        
+ Response 200 (application/json)

        {
            "status": "success",
            "message": "Address added successfully"
        }
        
        
## Remove Address [/remove_address]

### Remove Address [POST]

+ Header (application/json)

        {
            "Authorization":"Bearer dasljhvlaskvaf"
        }
        
+ Request (application/json)

        {
            "address_id":1
        }
        
+ Response 200 (application/json)

        {
            "status": "success",
            "message": "Address removed successfully"
        }
        
        
## Payment [/payment]

### Payment [POST]

+ Header (application/json)

        {
            "Authorization":"Bearer dasljhvlaskvaf"
        }
        
+ Response 200 (application/json)

        {
            "status": "success",
            "message": "Payment done successfully"
        }
        
        
## Apply Coupon [/apply_coupon]

### Apply Coupon [POST]

+ Header (application/json)

        {
            "Authorization":"Bearer dasljhvlaskvaf"
        }
        
+ Request (application/json)

        {
            "coupon_code":"XC234F"
        }
        
+ Response 200 (application/json)

        {
            "status": "success",
            "message": "Coupon applied successfully"
        }
        
        
## View Profile [/profile]

### Profile [GET]

+ Header (application/json)

        {
            "Authorization":"Bearer caksjcahksjascdasca"
        }

+ Response 200 (application/json)

        {
          "status":"success",
          "message":"successfully listed",
          "data":{
                "name":"Sithara Krishnakumar",
                "image_url":"https://i.ibb.co/kmrbPJp/22687832-1426096807440196-4276502542564884957-n.jpg",
                "email":"sithara@gmail.com",
                "phone": "9037324058"
                }
        }
        
        
## Edit Profile [/edit_profile]

### Edit Profile [POST]

+ Request (application/json)

        {
            "name": "abcd",
            "email": "abcd@efg.com",
            "password": "password",
            "phone": "9037324059",
            "gender": "Male"
        }
        
+ Response 200 (application/json)

        {
            "status": "success",
            "message": "profile updated successfully"
        }
        
        
## Wishlist [/wishlist]

### Wishlist [GET]

+ Header (application/json)

        {
            "Authorization":"Bearer caksjcahksjascdasca"
        }
        
+ Response 200 (application/json)

        {
            "status": "success",
            "message": "wishlist listed successfully",
            "data": [{"id":1,
                        "image":"https://i.ibb.co/GtymPQB/product-3.png",
                        "product_title":"Product 1",
                        "short_description":"Continental, Pan - Asian",
                        "actual_price":"200",
                        "discounted_price":"100"
                        },
                        {"id":2,
                        "image":"https://i.ibb.co/GtymPQB/product-3.png",
                        "product_title":"Product 2",
                        "short_description":"Continental, Pan - Asian",
                        "actual_price":"200",
                        "discounted_price":"100"
                        },
                        {"id":3,
                        "image":"https://i.ibb.co/GtymPQB/product-3.png",
                        "product_title":"Product 3",
                        "short_description":"Continental, Pan - Asian",
                        "actual_price":"200",
                        "discounted_price":"100"
                        },
                        {"id":4,
                        "image":"https://i.ibb.co/GtymPQB/product-3.png",
                        "product_title":"Product 4",
                        "short_description":"Continental, Pan - Asian",
                        "actual_price":"200",
                        "discounted_price":"100"
                        }]
        }
        
        
## Orders [/orders]

### Orders [GET]

+ Header (application/json)

        {
            "Authorization":"Bearer caksjcahksjascdasca"
        }
        
+ Response 200 (application/json)

        {
            "status": "success",
            "message": "orders listed successfully",
            "data": [{},{},{},{}]
        }
        
        
## Reviews [/reviews]

### Orders [GET]

+ Header (application/json)

        {
            "Authorization":"Bearer caksjcahksjascdasca"
        }
        
+ Response 200 (application/json)

        {
            "status": "success",
            "message": "orders listed successfully",
            "data": [{},{},{},{}]
        }
        
        
        
## Reviews [/notifications]

### Orders [GET]

+ Header (application/json)

        {
            "Authorization":"Bearer caksjcahksjascdasca"
        }
        
+ Response 200 (application/json)

        {
            "status": "success",
            "message": "Notifications listed successfully",
            "data": [{"id":1,"title":"Notification","description":"description","image_url":"https://i.ibb.co/j35w2rt/product-1.png"},
            {"id":2,"title":"Notification","description":"description","image_url":"https://i.ibb.co/j35w2rt/product-1.png"},
            {"id":3,"title":"Notification","description":"description","image_url":"https://i.ibb.co/j35w2rt/product-1.png"},
            {"id":4,"title":"Notification","description":"description","image_url":"https://i.ibb.co/j35w2rt/product-1.png"},
            {"id":5,"title":"Notification","description":"description","image_url":"https://i.ibb.co/j35w2rt/product-1.png"},
            {"id":6,"title":"Notification","description":"description","image_url":"https://i.ibb.co/j35w2rt/product-1.png"},
            {"id":7,"title":"Notification","description":"description","image_url":"https://i.ibb.co/j35w2rt/product-1.png"},
            {"id":8,"title":"Notification","description":"description","image_url":"https://i.ibb.co/j35w2rt/product-1.png"},
            {"id":9,"title":"Notification","description":"description","image_url":"https://i.ibb.co/j35w2rt/product-1.png"},
            {"id":10,"title":"Notification","description":"description","image_url":"https://i.ibb.co/j35w2rt/product-1.png"},
            {"id":11,"title":"Notification","description":"description","image_url":"https://i.ibb.co/j35w2rt/product-1.png"},
            {"id":12,"title":"Notification","description":"description","image_url":"https://i.ibb.co/j35w2rt/product-1.png"},
            {"id":13,"title":"Notification","description":"description","image_url":"https://i.ibb.co/j35w2rt/product-1.png"},
            {"id":14,"title":"Notification","description":"description","image_url":"https://i.ibb.co/j35w2rt/product-1.png"},
            {"id":15,"title":"Notification","description":"description","image_url":"https://i.ibb.co/j35w2rt/product-1.png"},
            {"id":16,"title":"Notification","description":"description","image_url":"https://i.ibb.co/j35w2rt/product-1.png"},
            {"id":17,"title":"Notification","description":"description","image_url":"https://i.ibb.co/j35w2rt/product-1.png"}]
        }